---
- name: Install required packages for firewalld
  package:
    name: "{{ firewalld_packages }}"
    state: present
  tags:
    - packages

- name: Configure firewalld service
  service:
    name: "{{ firewalld_service_name }}"
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"
  tags:
    - configuration
    - policy

- name: Enable firewalld services
  firewalld:
    service: "{{ item.name }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ firewalld_services_enable }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Disable firewalld services
  firewalld:
    service: "{{ item.name }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: disabled
  with_items:
    - "{{ firewalld_services_disable }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Adding PortProtocol Rules
  firewalld:
    port: "{{ item.port }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ firewalld_port_protocol_rule_add }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Delete PortProtocol Rules
  firewalld:
    port: "{{ item.port }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: disabled
  with_items:
    - "{{ firewalld_port_protocol_rule_delete }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Adding ipAddress Rules
  firewalld:
    source: "{{ item.address }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ firewalld_ipaddress_rule_add }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Delete ipAddress Rules
  firewalld:
    source: "{{ item.address }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: disabled
  with_items:
    - "{{ firewalld_ipaddress_rule_delete }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Adding Rich Rules
  firewalld:
    rich_rule: "rule family={{ item.family }} source address={{ item.address }} port port={{ item.port }} protocol={{ item.protocol }} {{ item.action }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ firewalld_rich_rule_add }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Removing Rich Rules
  firewalld:
    rich_rule: "rule family={{ item.family }} source address={{ item.address }} port port={{ item.port }} protocol={{ item.protocol }} {{ item.action }}"
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
    state: disabled
  with_items:
    - "{{ firewalld_rich_rule_delete }}"
  tags:
    - configuration
    - firewall
    - policy