---
- name: Install required packages for firewalld
  package:
    name: "{{ firewalld_packages }}"
    state: present
  tags:
    - packages

- name: Configure firewalld service
  service:
    name: "{{ firewalld_service_name }}"
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"
  tags:
    - configuration
    - policy

- name: Enable firewalld services
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ firewalld_services_enable }}"
  tags:
    - configuration
    - firewall
    - policy

- name: Disable firewalld services
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
  with_items:
    - "{{ firewalld_services_disable }}"
  tags:
    - configuration
    - firewall
    - policy
