---
- name: Install required packages for firewalld
  package:
    name: "{{ firewalls_required_packages }}"
    state: present
  tags:
    - packages

- name: Configure firewalld service
  service:
    name: "{{ firewalld_service_name }}"
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"
  tags:
    - configuration
    - policy
